spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portfolio
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    const:
      user: ${SECURITY_USER}
      password: ${SECURITY_PASSWORD}
    secret: ${SECURITY_SECRET:OFxmS2XjeLyhFIXLa6DOwbVCRziqIhqDWfOL8mQiRJM= }
    token-validity-time: 3600000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
